### ISSUE TITLE
[Icon Request] xtreme download manager (XDM)

### ISSUE THREAD

**Issue by Skolap** [vinceliuice/Tela-circle-icon-theme#106]
https://github.com/subhra74/xdm
https://xtremedownloadmanager.com/

**Comment by vinceliuice** [comment]
Xdm do not use icon theme, you need to edit the start desktop file

**Comment by Skolap** [comment]
Is it's icon included in icon pack?

**Comment by Skolap** [comment]
> Xdm do not use icon theme, you need to edit the start desktop file

Is it's icon included in icon pack?

**Comment by vinceliuice** [comment]
```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec="/opt/xdman/xdman"
Name=Xtreme Download Manager
Comment=Powerfull download accelarator and video downloader
Categories=Network;
Icon=/opt/xdman/icon.png
```

xdman use it's own icon in /opt/xdman

**Comment by vinceliuice** [comment]
You need to chang:
`Icon=/opt/xdman/icon.png`
to:
`Icon=xdman`

**Comment by Skolap** [comment]
OK, It worked. Thanks.
