### ISSUE TITLE
[Icon Request] Haruna Media Player

### ISSUE THREAD

**Issue by shakeelansari63** [vinceliuice/Tela-circle-icon-theme#107]
Please add Haruna Player icon which is QT frontend for MPV

**Comment by MolassesLover** [comment]
I added the icon in this pull request: https://github.com/vinceliuice/Tela-circle-icon-theme/pull/108.

If it doesn't get/hasn't yet been merged, you can use [GitHub CLI](https://cli.github.com/) to checkout.
```sh
➜ gh pr checkout 108
```

**Comment by vinceliuice** [comment]
Added now
