### ISSUE TITLE
[KolourPaint] Wrong icons for tools 

### ISSUE THREAD

**Issue by wilmhit** [vinceliuice/Tela-circle-icon-theme#11]
Some icons are duplicated/wrong in KolourPaint's toolbar. Image below. I checked and this is not a problem in Adwaita or Breeze.
| Icon now       | Should be     | Row  | Col    |
| :---------------- | :---------------: | :-----: | -------: |
|  Rectangles  | Rectangular selection   | 1    | 2 |
|  Circle  | Circular selection   | 2    | 1 |
|  Flood fill  | Color picker | 5    | 2 |
|  Rectangle  | Rounded rectangle | 7    | 1 |
|  Polygons  | Broken line | 9    | 1 |
|  1  | Zoom | 10    | 1 |

![Screenshot](https://user-images.githubusercontent.com/48449849/101671536-e646de00-3a54-11eb-922b-a918f2569b1c.png)

**Comment by vinceliuice** [comment]
Fixed now!
