### ISSUE TITLE
Question regarding  gtk-update-icon-cache

### ISSUE THREAD

**Issue by jubalh** [vinceliuice/Tela-circle-icon-theme#128]
Here in https://github.com/vinceliuice/Tela-circle-icon-theme/blob/master/install.sh#L218 you call gtk-update-icon-cache which you dont do in https://github.com/vinceliuice/Mojave-gtk-theme/blob/master/install.sh.
Is this really needed?

**Comment by vinceliuice** [comment]
Why do it in `Mojave-gtk-theme` ? it's not a icon theme, only icon theme need it for gnome desktop

**Comment by jubalh** [comment]
Oh sorry, sure!
I was confused :) Packaged several of your icon and gtk themes and seems like I lost the overview of what I'm trying to do.
