### ISSUE TITLE
Illegible icons in Libreoffice

### ISSUE THREAD

**Issue by human-V-oid** [vinceliuice/Tela-circle-icon-theme#142]
The dark icons are not legible in libreoffice, in both circle and normal themes with a dark theme applied.

![Screenshot_20230208_153703](https://user-images.githubusercontent.com/85420504/217506494-dad2f214-0ec8-4c45-be97-f70d6cfda43e.png)

**Comment by shakeelansari63** [comment]
> The dark icons are not legible in libreoffice, in both circle and normal themes with a dark theme applied.
> 
> ![Screenshot_20230208_153703](https://user-images.githubusercontent.com/85420504/217506494-dad2f214-0ec8-4c45-be97-f70d6cfda43e.png)

You need to change the icon theme inside Libreoffice. Libreoffice does not use Tela icon theme. 
Goto Tools > Options > LibreOffice (on left) > View > Icon style

And select a theme which suits you taste

**Comment by human-V-oid** [comment]
Thanks, but I can not find Tela Dark icons in there, although I can find some other dark icons. 
Thanks, but I can not find Tela Dark icons in there, although I can find some other dark icons. 

Is there a way to use Tela Dark Icons?
Is there a way to use Tela Dark Icons?

> > The dark icons are not legible in libreoffice, in both circle and normal themes with a dark theme applied.
> > ![Screenshot_20230208_153703](https://user-images.githubusercontent.com/85420504/217506494-dad2f214-0ec8-4c45-be97-f70d6cfda43e.png)
> 
> You need to change the icon theme inside Libreoffice. Libreoffice does not use Tela icon theme. Goto Tools > Options > LibreOffice (on left) > View > Icon style
> 
> And select a theme which suits you taste



> > The dark icons are not legible in libreoffice, in both circle and normal themes with a dark theme applied.
> > ![Screenshot_20230208_153703](https://user-images.githubusercontent.com/85420504/217506494-dad2f214-0ec8-4c45-be97-f70d6cfda43e.png)
> 
> You need to change the icon theme inside Libreoffice. Libreoffice does not use Tela icon theme. Goto Tools > Options > LibreOffice (on left) > View > Icon style
> 
> And select a theme which suits you taste


Thanks, but I can't find Tela Dark icons in there, although some other nice dark icons can be found.

Is there a way to use Tela Dark circle icons?

**Comment by fitojb** [comment]
This is a freedesktop icon theme, not a LibreOffice icon theme

**Comment by human-V-oid** [comment]
> This is a freedesktop icon theme, not a LibreOffice icon theme

I completely understand that I can't use freedesktop icon themes in Libreoffice.

Thanks.
