### ISSUE TITLE
Brave Broser Nightly build icon

### ISSUE THREAD

**Issue by johncaling40** [vinceliuice/Tela-circle-icon-theme#15]
Here is a brave browser nightly build icon

[brave-nightly.zip](https://github.com/vinceliuice/Tela-circle-icon-theme/files/5822598/brave-nightly.zip)

**Comment by johncaling40** [comment]
I would have made a pr but idk how to link it and stuff

**Comment by vinceliuice** [comment]
I'll add this

**Comment by johncaling40** [comment]
Thanks,
