### ISSUE TITLE
[Icon Request] GNS3

### ISSUE THREAD

**Issue by PercyDLR** [vinceliuice/Tela-circle-icon-theme#172]
**Tell me things about the app or icon**

>Build, Design and Test your network in a risk-free virtual environment and access the largest networking community to help. Whether you are studying for your first networking exam or building out a state-wide telecommunications network, GNS3 offers an easy way to design and build networks of any size without the need for hardware. And the best part is it's free!

1. App name: GNS3
2. App Webside: or App Github Homepage:  [web page](https://gns3.com/)
3. App icon name: gns3

**Additional context**

It's logo looks like this:

![image](https://github.com/vinceliuice/Tela-circle-icon-theme/assets/92818861/acd13a84-c926-4001-a873-e6d15e789806)

**Comment by vinceliuice** [comment]
Fixed
