### ISSUE TITLE
[Icon Request] [Mozc]

### ISSUE THREAD

**Issue by SakanaBook** [vinceliuice/Tela-circle-icon-theme#174]
1. Mozc
2. https://github.com/google/mozc
3. Mozcの設定

Additional context:
Mozc is  a Japanese Input Method Editor.
It is used by most Japanese people.
If possible, please support other apps related to Mozc. (IBus, Fcitx5, Fcitx, etc.)

**Comment by vinceliuice** [comment]
Fixed
