### ISSUE TITLE
[Icon request] Apache Directory Studio

### ISSUE THREAD

**Issue by ayron86** [vinceliuice/Tela-circle-icon-theme#193]
**1. App name:** Apache Directory Studio
**2. App Webside:** (https://directory.apache.org/studio/)
**3. App icon name:** org.apache.directory.studio
**4. Provided .desktop file:**

```
[Desktop Entry]
Type=Application
Name=Apache Directory Studio
Comment=A complete directory tooling platform, intended to be used with any LDAP server
Icon=org.apache.directory.studio
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=ApacheDirectoryStudio org.apache.directory.studio
Terminal=false
Categories=Office;Database;
Keywords=ldap;ldif;
X-Flatpak=org.apache.directory.studio
```
**5. Default Icon:**
![icon](https://github.com/vinceliuice/Tela-circle-icon-theme/assets/29458646/24f892f7-f5ef-4281-b3ac-fc1674b7721c)

**Comment by shakeelansari63** [comment]
Created PR with this Icon - #200

**Comment by ayron86** [comment]
> Created PR with this Icon - #200

Nice!!! I like it. I consider this to be one of the best Linux icon themes

**Comment by shakeelansari63** [comment]
The icon is now available in the pack. Should be good to close this issue.
