### ISSUE TITLE
When using KDE Plasma 6, symbolic icons in the system-tray widget are not consistent anymore

### ISSUE THREAD

**Issue by ProstMeister** [vinceliuice/Tela-circle-icon-theme#195]
**Describe the bug**
When using KDE Plasma 6, symbolic icons in the system-tray widget are not consistent anymore: for some indicators (klipper, WiFi, Firewall applet, display configuration) a full-color icon is used instead of the monochromatic one.

**To Reproduce**
1. Prepare a VM based on a distro that offers KDE Plasma 6 as DE (EndeavourOS, Arch, KDE Neon, etc)
2. Setup a panel with system-tray widget
3. Install and apply the tela-circle-dark icon theme 
4. Observe the colorful icons in the system tray

**Expected behavior**
Only monochromatic icons should be used as indicator icons.

**Screenshots**
![image](https://github.com/vinceliuice/Tela-circle-icon-theme/assets/66740513/2f7eeb71-b03a-4cd1-965f-668875c64692)
![image](https://github.com/vinceliuice/Tela-circle-icon-theme/assets/66740513/2da3c6c6-eced-421d-a296-62c8be3a4bdc)

**Desktop (please complete the following information):**
 - OS: Endeavour OS Galileo
 - App KDE Plasma DE
 - Version 6.xx

**Additional context**
The bug is caused by the fact that in KDE Plasma 6 some symbolic icons have been renamed, hence the link between the indicator and the icon itself got broken. I already submitted a bug in KDE: https://bugs.kde.org/show_bug.cgi?id=483082 that was closed because apparently icon packs developers have been warned with months in advance about this change.

**Comment by vinceliuice** [comment]
What about now ?

**Comment by ProstMeister** [comment]
> What about now ?

It has been fixed a while ago.

**Comment by ProstMeister** [comment]
Issue fixed
