### ISSUE TITLE
Folders icons on Xfce 4.14 are squared

### ISSUE THREAD

**Issue by cialu** [vinceliuice/Tela-circle-icon-theme#2]
Hi, I'm using this theme on openSUSE 15.2 with Xfce 4.14 and it's working like a charm, but the folders icons are squared like the Tela-icon-theme's ones and not circled.

Thanks for your work.
Regards.

![Screenshot_2020-06-12_08-37-17](https://user-images.githubusercontent.com/1382127/84472727-05240d80-ac88-11ea-959b-6dfc507ae9b3.png)

**Comment by vinceliuice** [comment]
I forgot update the README file, Run `./install -c` you can have circle one

**Comment by cialu** [comment]
> I forgot update the README file, Run `./install.sh -c` you can have circle one

Thanks for the answer. I'll try to download and install from **GitHub**, but I have used the files downloaded from **Pling** ([https://www.pling.com/p/1359276/](https://www.pling.com/p/1359276/)) and moved to the `/home/user/local/share/themes` folder.

**Comment by vinceliuice** [comment]
`$HOME/.local/share/themes` I remember this is the path of gtk theme

**Comment by cialu** [comment]
> `$HOME/.local/share/themes` I remember this is the path of gtk theme

Yes, I forgot the `.` dot on local, but I did right on the PC. Also, tested `$HOME/.themes/` with same result. Folders are squared and not circled.

**Comment by vinceliuice** [comment]
Icon theme  folder is $Home/.local/share/icons

**Comment by cialu** [comment]
Sorry for the mistake, I will try to be clearer. I have tested the theme taken from **Pling** both in `$Home/.local/share/icons/` as in `$Home/.icons/` and the result is the same with squared folders rather than circular folders. As soon as I have time I'll try to install this theme from **GitHub** through the option you mentioned above.

**Comment by vinceliuice** [comment]
I didn't upload circle version on pling,  you can only install it from github

**Comment by cialu** [comment]
> I didn't upload circle version on pling, you can only install it from github

Ok, perfect. Thank you so much for your kindness.
