### ISSUE TITLE
[Icon Request] IntelliJ / Vscode

### ISSUE THREAD

**Issue by Arrowsome** [vinceliuice/Tela-circle-icon-theme#33]
These two IntelliJ/Visual Studio Code have no proper icons and thus ruins the experience of this icon pack

**Comment by ShayBox** [comment]
There's both VSC and Intellij icons, whatever package manager you're using (aur/jetbrains toolbox) don't use the correct icon names or a direct path to their own icons

**Comment by edraft** [comment]
Compared to others, these aren't proper icons, are they?

![image](https://user-images.githubusercontent.com/44439074/140759060-0e84edbf-1c77-4cf4-bf9f-fe1a511c3be2.png)

**Comment by vinceliuice** [comment]
Pycharm not use icon theme

**Comment by PercyDLR** [comment]
If it bothers you too much, you could modify the icon with `sudoedit /usr/share/applications/visual-studio-code.desktop` and change the default 
`Icon=visual-studio-code` with 
`Icon=/opt/visual-studio-code/resources/app/resources/linux/code.png` (which is the logo with transparent background)
or specify the path to another image
