### ISSUE TITLE
[Icon Request] List

### ISSUE THREAD

**Issue by idontlikecaesar** [vinceliuice/Tela-circle-icon-theme#38]
- 0 a.d
- Tootle
- Giara
- Spot
- Freetube
- Dialect
- OTPClient
- Hedgewars
- Xonotic

These icons are missing and I think this icon pack is the most beautiful that is available. Please consider making these icons. Thank you.

**Comment by DAnaeto** [comment]
+1 on freetube. Great icon pack!

**Comment by vinceliuice** [comment]
Added
