### ISSUE TITLE
[Icon Request] Zoom

### ISSUE THREAD

**Issue by nihakuto** [vinceliuice/Tela-circle-icon-theme#39]
Hi, could you please add a **_tray_** icon for Zoom? The default sticks out like a sore thumb. Thanks!

**Tell me things about the app or icon**

1. App name: Zoom
2. App Website: https://zoom.us
3. App icon name: Zoom.svg

**Additional context**

The only zoom icon i could find was the app icon for the circle theme. 

https://zoom.us/download#client_4meeting
https://aur.archlinux.org/packages/zoom/

![image](https://user-images.githubusercontent.com/34426136/118147443-92fb0200-b3dd-11eb-9b13-46c3093733ad.png)

**Comment by vinceliuice** [comment]
Added
