### ISSUE TITLE
[question] Help in adding a new file/mime icon

### ISSUE THREAD

**Issue by yozachar** [vinceliuice/Tela-circle-icon-theme#46]
Hi, I was trying to add a icon for [`.nim`](https://nim-lang.org/)  files.

---

`/Tela-circle-blue/16/mimetypes/`

- application-x-nim-bytecode ![application-x-nim-bytecode 16](https://user-images.githubusercontent.com/38415384/124357880-5e683180-dc3b-11eb-815a-ef533d5d2a7c.png)

- text-x-nim ![text-x-nim 16](https://user-images.githubusercontent.com/38415384/124357890-66c06c80-dc3b-11eb-9e59-1536c27ebd1f.png)

---

`/Tela-circle-blue/16/mimetypes/`

- application-x-nim-bytecode ![application-x-nim-bytecode 22](https://user-images.githubusercontent.com/38415384/124357829-28c34880-dc3b-11eb-9d3b-938bb87c9b93.png)

- text-x-nim ![text-x-nim 22](https://user-images.githubusercontent.com/38415384/124357901-73dd5b80-dc3b-11eb-8889-dedbd0664485.png)

---

`/Tela-circle-blue/scalable/mimetypes/`

- text-x-nim ![text-x-nim 64](https://user-images.githubusercontent.com/38415384/124357928-90799380-dc3b-11eb-9f69-1d918ce99da1.png)

---

`/Tela-circle-blue/scalable/apps/`

- nim ![nim](https://user-images.githubusercontent.com/38415384/124357950-a6875400-dc3b-11eb-85bf-68d56326f89e.png)

---

But when I put them in icons folder (`/usr/share/icons/Tela-circle-blue`) I see no difference:

![image](https://user-images.githubusercontent.com/38415384/124358110-6ffe0900-dc3c-11eb-8c61-c6c8ac2e981b.png)

Can you please help me to figure out what's missing?

> PS: I have the svg files, and am happy to provide them whenever needed.

**Comment by vinceliuice** [comment]
Open this file properties, and tell me the file type introduction like this:
![Screenshot_20210704_124245](https://user-images.githubusercontent.com/7604295/124373515-6967a400-dcc5-11eb-9d9f-7c418680ff1e.png)

**Comment by joe733** [comment]
![image](https://user-images.githubusercontent.com/38415384/124387760-5a044d00-dcfd-11eb-917f-becc7b2a4e11.png)

I'm using Thunar, but I think your looking for `kind` of the file. It says `plain text`.

```dart
~/Templates/prog 
➜ file python.py 
python.py: Python script, ASCII text executable

~/Templates/prog 
➜ file nim.nim 
nim.nim: ASCII text

```

Hmm.. interesting, so the system doesn't know it's a `.nim` file yet.

**Comment by vinceliuice** [comment]
Linux distinguishes the file type according to the content of the file, and has nothing to do with the file name suffix

**Comment by joe733** [comment]
Yes, that's correct, let me ask about this in nim community.

**Comment by joe733** [comment]
**Update**: A [patch](https://github.com/file/file/commit/9389daad580bf31dee3e84b04fd675542f263bae) as been made to identify `nim-lang`. I'll comment once I'm able to test it.

**Comment by Yardanico** [comment]
@joe733 if you're still curious - that's because the patch that "added" Nim support to `file` was wrong - it was _specifically_ made for one single file and wasn't checked thoroughly, I've opened another issue, see https://bugs.astron.com/view.php?id=293
