### ISSUE TITLE
Discord icon

### ISSUE THREAD

**Issue by Zumiito** [vinceliuice/Tela-circle-icon-theme#5]
He is a insurgent! xD

![Captura de pantalla de 2020-08-10 14-09-16](https://user-images.githubusercontent.com/65167650/89781421-93473380-db13-11ea-8f0e-5fa47f1bf28c.png)
![Captura de pantalla de 2020-08-10 14-08-17](https://user-images.githubusercontent.com/65167650/89781432-980be780-db13-11ea-98a5-a8a9960dd061.png)

Thanks for your job, great icons pack

**Comment by vinceliuice** [comment]
No problem! I'll add this

**Comment by vinceliuice** [comment]
Could you tell me which way you installed Discord?

**Comment by Zumiito** [comment]
> Could you tell me which way you installed Discord?

I use Fedora 32 GNOME, " sudo dnf install discord"
