### ISSUE TITLE
[Icon Request] Pop!_OS Applications/Launcher/Workspaces

### ISSUE THREAD

**Issue by hlucas13** [vinceliuice/Tela-circle-icon-theme#53]
I would like, if possible, to add an icon for Pop!_OS Show Applications, Show Launcher, and Show Workspaces.

**Comment by slottwo** [comment]
Informations that may help resolve this Icon Request.

The Pop_OS! Comic treats these buttons as applications and can be found in the utilities folder of the application overview:
![image](https://user-images.githubusercontent.com/41028091/150143735-0a7023b8-c9fa-4c1e-933e-597e5b65e9e8.png)

And the names of these icons are:

- pop-cosmic-applications
- pop-cosmic-launcher
- pop-cosmic-workspaces

![image](https://user-images.githubusercontent.com/41028091/150145645-18c4f333-de8e-4d93-84e7-28693472455e.png)
