### ISSUE TITLE
[Request/Bug] Discord icon is bit bigger than other icons???

### ISSUE THREAD

**Issue by xelser** [vinceliuice/Tela-circle-icon-theme#67]
![Screenshot from 2021-12-25 06-27-45](https://user-images.githubusercontent.com/81435783/147373474-8f6c240a-68a6-4a15-b5bb-996ecfca256f.png)

The title says it. It sticks out like a sore thumb. Would be nice if it is consistent size compare to others. Thanks 😃

**Comment by MolassesLover** [comment]
I checked the `.svg` file and the dimensions, everything seems alright. I'm assuming this is an issue on your end, maybe you aren't up to date?

I updated the icon, though! Here's the [pull request](https://github.com/vinceliuice/Tela-circle-icon-theme/pull/68).

![discord](https://user-images.githubusercontent.com/60114762/147373951-c9dce39e-8cd0-483b-8824-b49862acfbc8.png)

**Comment by vinceliuice** [comment]
That's because this one not using the theme icons, not the icon size issue

**Comment by xelser** [comment]
I'll check later. I dont have my computer with me. I installed it along with other packages using `dnf` command. All repos that i have is from Fedora, google-chrome (3rd party repo from fedora) and RPM fusion.

**Comment by xelser** [comment]
```
[Desktop Entry]
Name=Discord
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/usr/bin/Discord
Icon=/usr/lib64/discord/discord.png
Type=Application
Categories=Network;InstantMessaging;
Path=/usr/bin
X-Desktop-File-Install-Version=0.26
```

This is the `.desktop` file of discord. I assume I'll just need to change the icon path?

**Comment by xelser** [comment]
fixed it thanks for the heads up 👍🏼 much appreciated

**Comment by vinceliuice** [comment]
You are welcome
