### ISSUE TITLE
[Icon Request] Heroic Games Launcher

### ISSUE THREAD

**Issue by redromnon** [vinceliuice/Tela-circle-icon-theme#71]
**Tell me things about the app or icon**
1. App name: Heroic Games Launcher
2. App Github Homepage: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher
3. App icon name: heroic
   
It's one of the most popular apps right now, so I guess it's worth creating an icon for it.

**Comment by MolassesLover** [comment]
![heroic](https://user-images.githubusercontent.com/60114762/162530875-a179770c-41ba-4319-959c-b9fea69c5c66.svg)

**Comment by redromnon** [comment]
Looks good!

**Comment by MolassesLover** [comment]
Awesome, would you mind closing this pull request?
