### ISSUE TITLE
[Icon Request] Warpinator

### ISSUE THREAD

**Issue by xelser** [vinceliuice/Tela-circle-icon-theme#72]
A very easy and useful p2p sharing application from Linux mint. Would love to have it in this icon theme. Thanks

**Comment by MolassesLover** [comment]
Hiya, I finished the Warpinator icon up, it's available on my fork. I'll make a pull request for this repository later.
![warpinator](https://user-images.githubusercontent.com/60114762/151222434-22d6c6aa-4b4a-465a-a267-55c6c694c4bd.png)

**Comment by xelser** [comment]
thanks 👍🏼
