### ISSUE TITLE
Onlyoffice icon is square

### ISSUE THREAD

**Issue by werdahias** [vinceliuice/Tela-circle-icon-theme#74]
I installed the icon theme, yet onlyoffice has a square icon:

![image](https://user-images.githubusercontent.com/23419969/153737644-df5b9fc4-6562-4068-af6c-2a13ad4bbd08.png)

**Comment by PercyDLR** [comment]
Looking the icon set, I found that there ARE icons for only office, and are these:
![Screenshot_2022-03-19_19:13:42](https://user-images.githubusercontent.com/92818861/159142658-c5744414-0f2f-4464-aa4b-f688dd868888.png)
In case you still have this problem, you could check the libreoffice .desktop file in `/usr/share/applications` and make sure the icon field contains:
`Icon=onlyoffice`

**Comment by MolassesLover** [comment]
Please close this issue
