### ISSUE TITLE
Color Nord does not work for circle folder version

### ISSUE THREAD

**Issue by mseveritt** [vinceliuice/Tela-circle-icon-theme#75]
Dear Vince,
many thanks for considering a Nord color version of Tela Circle.
Unfortunately, it does not work in the circle folder version.
Is it possible to fix that?
Also, not all nord color variants of Graphite and Colloid GTK theme are represented. If it is too much to ask to include them all, is it possible to include at least the one of Papirus' Nordic version which matches 'teal nord'?
Many thanks in advance.

**Comment by vinceliuice** [comment]
No problem!

**Comment by MolassesLover** [comment]
I added a circular version of the Nord colour theme. I don't have experience with Graphite or Colloid so I didn't make any teal Nord folders. Sorry for the inconvenience, I'll see if I can add those soon!

**Comment by mseveritt** [comment]
Thanks MolassesLover.
 If you are heading in the direction of including more norded colours you can also check Vince’s Colloid icon theme where it is already implemented.
Maybe you just take the existing colours of Tela and create norded versions of them (black seems already done with ‚nord‘).
Cf. https://www.nordtheme.com/docs/colors-and-palettes

**Comment by MolassesLover** [comment]
I tend to use multiple folder colours across my desktop environment; I think I am going to make a new branch for all the Nord colours. In that branch red could be based around the Aurora red `#bf616a`, for example. 

--------
![default-folder](https://user-images.githubusercontent.com/60114762/161439702-1fafe4ef-081f-4e9e-972c-7621e723558d.svg)

**Comment by mseveritt** [comment]
That sounds like a plan. Your Aurora red folder looks very nice. Mabye you can bring this into tela-icon-theme as well as a new branch.
