### ISSUE TITLE
ScanTailor

### ISSUE THREAD

**Issue by michal-devel** [vinceliuice/Tela-circle-icon-theme#79]
**Tell me things about the app or icon**
1. App name: ScanTailor Advanced
2. App Github Homepage: https://github.com/4lex4/scantailor-advanced
3. App icon name: ScanTailor

**Additional context**
First of all, thank you very much for you great icon set!

Scan Tailor is an interactive post-processing tool for scanned pages. It is a great tool that has no alternatives. A flat design icon would be great. Here's the original icon (it's kind of ugly if you ask me).

Thanks in advance!

![ScanTailor](https://user-images.githubusercontent.com/28739278/151701928-a985ada5-96d2-4cd1-92fa-67ccd9372ba7.svg)

**Comment by MolassesLover** [comment]
I'll take a look at it sometime! In any case, I think the scanner icon would suit it as a temporary fix.

**Comment by michal-devel** [comment]
Please take your time. I'm very happy your are are willing to make this icon. I will wait and use the icon you recommend for the time being. Cheers!

**Comment by michal-devel** [comment]
Dear @MolassesLover this is a friendly reminder of this icon request. I know you've taken a break but perhaps you have some spare time. Thanks!

**Comment by MolassesLover** [comment]
> Dear @MolassesLover this is a friendly reminder of this icon request. I know you've taken a break but perhaps you have some spare time. Thanks!

I tried making this icon but I'm genuinely stuck as to what it should be, and how to make it fit. Any ideas?

**Comment by michal-devel** [comment]
Perhaps a book on a flatbed scanner? A scanner icon is a bit generic, but a scanner with a book on it implies a software dealing with scanning of books.

**Comment by MolassesLover** [comment]
Welp, my drawing tablet ended up breaking while making the icon.
https://github.com/vinceliuice/Tela-circle-icon-theme/pull/100#issue-1353423221
