### ISSUE TITLE
[Icon Request] Unity Hub/Editor and ExifCleaner

### ISSUE THREAD

**Issue by airvue** [vinceliuice/Tela-circle-icon-theme#9]
Could you please add an icon for [ExifCleaner](https://exifcleaner.com/). 

![exifcleaner](https://user-images.githubusercontent.com/53982860/98735613-888d7c00-2358-11eb-9128-6a2f33957393.png)

The default does not scale properly with the other icons.

And an icon for Unity Hub/Editor, the default icon is grainy, so I am currently using another.

![unity](https://user-images.githubusercontent.com/53982860/98736223-65af9780-2359-11eb-9ad1-25f1b0e91846.png)

**Comment by vinceliuice** [comment]
No problem!
